name: Update README Date

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight (UTC)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the GITHUB_TOKEN for authentication

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Update README with current date
        run: |
          sed -i "s/Last Update: [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/Last Update: $CURRENT_DATE/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with current date"
          git push
